config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :estoque

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  get 'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',   as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect', as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page', as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :tamanhos

  resources :colecoes

  resources :linhas

  resources :tipos

  resources :cores

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'dashboard#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  include Arquivar

  has_many :vendas, dependent: :restrict_with_error

  scope :por_letra, -> (letra) { where(["nome like ?", "#{letra}%"]) }
  default_scope -> { order(:nome) }

  validates :nome, length: { maximum: 60 }, presence: true

  validate :data_aniversario

  { email:     40,
    fone_res:  20,
    fone_com:  20,
    fone_cel:  20,
    endereco:  60,
    bairro:    30,
    cep:       10,
    cidade:    60,
    uf:        2,
    obs:       100
  }.each do |key, val|
    validates key, length: { maximum: val },  allow_blank: true
  end

  def fone
    fone_cel || fone_res || fone_com
  end

  def aniversario
    unless aniver_dia.blank? || aniver_mes.blank?
      "#{aniver_dia.to_s.rjust(2, '0')}/#{aniver_mes.to_s.rjust(2, '0')}"
    end
  end

  def aniversario=(aniver)
    a = aniver.split("/")
    write_attribute(:aniver_dia, a[0])
    write_attribute(:aniver_mes, a[1])
  end


  def self.letras
    Cliente.all.map {|c| c.nome.try(:first).try(:upcase) }.uniq.sort
  end

private

  def data_aniversario
    errors.add(:aniversario, "Data Inválida") if aniver_dia.blank? != aniver_mes.blank?
    unless aniver_dia.blank? && aniver_mes.blank?
      dt = Date.new(2001, aniver_mes.to_i, aniver_dia.to_i) rescue nil
      errors.add(:aniversario, 'Data Inválida') unless dt
    end
  end

end

app/controllers/clientes_controller.rb
# coding: UTF-8
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy, :arquivar]

  def index
    params[:q] = { arquivado_eq: false } unless params[:q]

    if params[:letra]
      @search = Cliente.search(params[:q])
      @clientes = @search.result.por_letra(params[:letra]).order(:nome)
    else
      @search = Cliente.search(params[:q])
      @clientes = @search.result.order(:nome)
    end
    set_back_from(:cliente_show)
  end

  def show
    set_back_from(:venda_show)
  end

  def new
    @cliente = Cliente.new
  end

  def edit
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      redirect_to @cliente, notice: 'Cliente criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @cliente.update(cliente_params)
      redirect_to @cliente, notice: 'Cliente atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @cliente.destroy
      redirect_to clientes_path, notice: 'Cliente apagado com sucesso.'
    else
      flash[:error] = "Não foi possível apagar este cliente"
      render action: 'edit'
    end
  end

  def arquivar
    @cliente.arquivar! params[:desarquivar].blank?
    notice = params[:desarquivar].blank? ? "Arquivada" : "Desarquivada"
    redirect_to clientes_path, notice: "#{@cliente.nome} <b>#{notice}</b> com sucesso."
  end

  private

  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  def cliente_params
    params.require(:cliente)
          .permit(:nome, :email, :fone_res, :fone_com, :fone_cel, :endereco, :bairro, :cep, :cidade, :uf, :obs, :aniversario)
  end

end

app/helpers/clientes_helper.rb
module ClientesHelper

  def links_letras
    lis = Cliente.letras.map do |letra|
      content_tag(:li, class: (params[:letra] == letra) ? 'active' : '') do
        link_to letra, clientes_path(letra: letra)
      end
    end

    content_tag(:ul, lis.join("\n").html_safe, class: 'pagination')
  end

end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>

  <div class="row">
    <div class="col-sm-5 col-md-6">
      <%= f.input :nome, label: 'Nome', input_html: { class: 'input-lg' } %>
    </div>
    <div class="col-sm-5 col-md-4">
      <%= input_group(f, :email, label: 'email', icon: :envelope) %>
    </div>
    <div class="col-sm-2 col-md-2">
      <%= f.input :aniversario, label: "Aniversário", placeholder: 'dd/mm' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <%= input_group(f, :fone_cel, label: 'Celular', icon: :phone) %>
    </div>
    <div class="col-sm-4">
      <%= input_group(f, :fone_res, label: 'Fone Residencial', icon: :phone_alt) %>
    </div>
    <div class="col-sm-4">
      <%= input_group(f, :fone_com, label: 'Fone Comercial', icon: :phone_alt) %>
    </div>
    <div class="col-sm-6">
      <%= f.input :endereco, label: 'Endereco' %>
    </div>
    <div class="col-sm-4">
      <%= f.input :bairro, label: 'Bairro' %>
    </div>
    <div class="col-sm-2">
      <%= f.input :cep, label: 'CEP' %>
    </div>
    <div class="col-sm-4">
      <%= f.input :cidade, label: 'Cidade' %>
    </div>
    <div class="col-sm-2">
      <%= f.input :uf, label: 'UF' %>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-12">
      <%= f.input :obs, label: 'Obs' %>
    </div>

  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Cliente', class: 'btn btn-primary' %>

    <% unless @cliente.new_record?  %>

      <% if @cliente.arquivado? %>
        <%= link_to icon(:folder_close, 'Desarquivar este Cliente'),
            arquivar_cliente_path(@cliente, desarquivar: true),
            method: :post,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-success pull-right' %>
      <% else %>
        <%= link_to icon(:folder_open, ' Arquivar este Cliente'),
            arquivar_cliente_path(@cliente),
            method: :post,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-info pull-right' %>
      <% end %>

      <%= link_to icon(:trash, 'Apagar este Cliente'),
            @cliente,
            method: :delete,
            data: { confirm: 'Tem certeza?' },
            class: 'btn btn-sm text-danger pull-right' %>

    <% end %>
  </div>

<% end %>

app/views/clientes/edit.html.erb
<%= page_header "Editar Cliente" do %>

  <%= link_to icon(:chevron_left, "Voltar"), cliente_path(@cliente), class: 'btn' %>

<% end %>

<%= render 'form' %>

app/views/clientes/index.html.erb
<%= page_header "Clientes" do %>
  <%= link_to(icon(:plus, 'Novo Cliente'), new_cliente_path, class: 'btn btn-primary') %>
<% end %>

<div class="text-center affix1" data-offset-top="70"><%= links_letras %></div>

<div class="row">

  <div class="col-md-9">

    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>email</th>
          <th>Fone</th>
          <th>Aniver</th>
          <th>Vendas</th>
        </tr>
      </thead>
      <tbody>
        <% @clientes.each do |cliente| %>
          <tr>
            <td><%= link_to cliente.nome, cliente %></td>
            <td><small><%= cliente.email %></small></td>
            <td><%= cliente.fone %></td>
            <td><%= cliente.aniversario %></td>
            <td class="right"><%= label_estoque(cliente.vendas.count) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p class="index_count"><span><%= @clientes.count %></span> clientes encontradas.</p>

  </div>

  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Filtros</h3>
      </div>
      <div id="filtro_pedidos" class="panel-body">
        <%= simple_form_for @search, url: clientes_path, method: 'GET' do |f| %>
          <%= f.input :nome_cont, label: "Nome" %>
          <%= f.input :arquivado_eq, label: "Exibir Arquivados", as: :boolean %>

          <%= f.submit 'Filtrar', class: 'btn btn-info' %>
          <%= button_tag 'Limpar', class: 'btn btn-default clear' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clientes/new.html.erb
<%= page_header "Novo Cliente" do %>
  <%= link_to icon(:chevron_left, "Voltar"), clientes_path, class: 'btn' %>
<% end %>

<%= render 'form' %>

app/views/clientes/show.html.erb
<%= page_header "Exibir Cliente" do %>
  <%= link_to_back get_back_for(:cliente_show) %>
  <%= link_to icon(:edit, 'Editar Cliente'), edit_cliente_path(@cliente), class: 'btn btn-primary' %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">

    <h4 class="text-primary">
      <%= @cliente.nome %>
    </h4>

    <div class="row">

      <div class="col-md-4 col-sm-6">

        <dl class="dl-horizontal form">

          <dt>Email</dt>
          <dd><%= @cliente.email %></dd>
          <dt>Celular</dt>
          <dd><%= @cliente.fone_cel %></dd>

        </dl>

      </div>

    </div>

  </div>
</div>

<table class="table">
  <tbody>
    <% @cliente.vendas.includes(itens: { item: [:produto, :cor, :tamanho] }).order(data: :desc).each do |venda| %>
      <tr class='header'>
        <td colspan="10"> <%= venda.data %> &nbsp;&nbsp;&nbsp; <%= link_to venda.descr, venda %>   </td>
      </tr>
      <% venda.itens.each do |item| %>
      <tr>
        <td><%= item.produto.ref %></td>
        <td><%= item.produto.tipo.descricao %></td>
        <td><%= item.produto.fornecedor.nome %></td>
        <td><%= item.tamanho.try :nome %></td>
        <td><%= item.cor.try :nome %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>