config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :estoque

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  get 'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',   as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect', as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page', as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :tamanhos

  resources :colecoes

  resources :linhas

  resources :tipos

  resources :cores

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'dashboard#index'

end

app/models/ajuste.rb
class Ajuste < ActiveRecord::Base

  has_many :itens, class_name: 'ItemEstoque', as: :movimento, dependent: :destroy

  validates :tipo, presence: true, inclusion: { in: ['E', 'S'] }

  def adiciona_item!(bc)

    item = Item.find_or_create_by_barcode(bc)

    itens.create!(item_id: item.id, tipo: self.tipo)

  end

  def data
    created_at.to_date
  end

end

app/controllers/ajustes/itens_controller.rb
class Ajustes::ItensController < ApplicationController

  before_action :set_ajuste

  def create
    @item = @ajuste.adiciona_item!(params[:barcode])
  end

  def destroy
    @ajuste.itens.find(params[:id]).destroy!
  end

 private

  def set_ajuste
    @ajuste = Ajuste.find(params[:ajuste_id]) if params[:ajuste_id]
  end

end

app/controllers/ajustes_controller.rb
# coding: UTF-8
class AjustesController < ApplicationController
  before_action :set_ajuste, only: [:show, :edit, :update, :destroy]

  def index
    @search = Ajuste.search(params[:q])
    @ajustes = @search.result.order(:tipo)
    set_back_from(:ajuste_show)
  end

  def show
    @itens =  @ajuste.itens
                    .includes(item: [:tamanho, :cor, produto: [:fornecedor, :colecao]])
                    .order('colecoes.id desc, produtos.ref, itens.tamanho_id')
  end

  def new
    @ajuste = Ajuste.new
  end

  def edit
  end

  def create
    @ajuste = Ajuste.new(ajuste_params)

    if @ajuste.save
      redirect_to ajustes_path, notice: 'Ajuste criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @ajuste.update(ajuste_params)
      redirect_to ajustes_path, notice: 'Ajuste atualizado com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @ajuste.destroy
    redirect_to ajustes_path, notice: 'Ajuste apagado com sucesso.'
  end

  private
    def set_ajuste
      @ajuste = Ajuste.find(params[:id])
    end

    def ajuste_params
      params.require(:ajuste).permit(:tipo, :obs)
    end
end

app/helpers/ajustes/itens_helper.rb
module Ajustes::ItensHelper
end

app/helpers/ajustes_helper.rb
module AjustesHelper

  def label_es(es)
    case es.upcase
    when 'E'
      content_tag(:span, 'ENTRADA', class: 'label label-success')
    when 'S'
      content_tag(:span, 'SAÍDA', class: 'label label-danger')
    else
      content_tag(:span, es, class: 'label label-default')
    end
  end

end

app/views/ajustes/_form.html.erb
<%= simple_form_for(@ajuste) do |f| %>

  <div class="row">
    <div class="col-md-2">
      <%= f.input :tipo, label: 'Tipo', collection: [['Entrada', 'E'], ['Saída', 'S']], as: :radio_buttons %>
    </div>
    <div class="col-md-10">
      <%= f.input :obs, label: 'Descrição' %>
    </div>
  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Ajuste', class: 'btn btn-primary' %>

    <%= link_to icon(:trash, 'Apagar este Ajuste'),
                  @ajuste,
                  method: :delete,
                  data: { confirm: 'Tem certeza?' },
                  class: 'btn btn-sm text-danger pull-right' unless @ajuste.new_record? %>
  </div>
<% end %>

app/views/ajustes/edit.html.erb
<%= page_header "Editar Ajuste" do %>

  <%= link_to icon(:chevron_left, "Voltar"), ajustes_path, class: 'btn' %>

<% end %>

<%= render 'form' %>

app/views/ajustes/index.html.erb
<%= page_header "Ajustes de Estoque" do %>
  <%= link_to icon(:chevron_left, "Voltar"), estoque_index_path, class: 'btn' %>
  <%= link_to(icon(:plus, 'Incluir Ajuste'), new_ajuste_path, class: 'btn btn-primary') %>
<% end %>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Data</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @ajustes.each do |ajuste| %>
      <tr>
        <td><%= link_to ajuste.data, ajuste_path(ajuste) %></td>
        <td><%= label_es(ajuste.tipo) %></td>
        <td><small><%= ajuste.obs %></small></td>
        <td class="right">
          <span class="badge">
            <%= ajuste.itens.count %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="index_count"><span><%= @ajustes.count %></span> ajustes encontradas.</p>

app/views/ajustes/new.html.erb
<%= page_header "Novo Ajuste" do %>
  <%= link_to icon(:chevron_left, "Voltar"), ajustes_path, class: 'btn' %>
<% end %>

<%= render 'form' %>

app/views/ajustes/show.html.erb
<%= page_header "Ajuste de Estoque ##{@ajuste.id} &nbsp;&nbsp;&nbsp; #{label_es(@ajuste.tipo)}" do %>
  <%= link_to_back get_back_for(:ajuste_show) %>
  <%= link_to icon(:edit, 'Editar Ajuste'), edit_ajuste_path(@ajuste), class: 'btn btn-sm btn-primary' %>
<% end %>

<div class="well well-sm show">

  <div class="row">

    <div class="col-sm-10 big">
      <%= @ajuste.obs %>
      <small><%= l @ajuste.created_at.to_date, format: :medium %></small>
    </div>

    <div class="col-sm-2 big">
      <span id="itens_count"><%= @ajuste.itens.count %></span> <small>peças</small>
    </div>


  </div>

</div>

<div class="row">

  <div class="col-md-12">

    <div class="panel panel-info">
      <div class="panel-heading">
        <b class="panel-title">Peças Incluídas</b>

        <%= form_tag(ajuste_itens_path(@ajuste), remote: true ) do %>
          <%= text_field_tag :barcode,
                              nil,
                              maxlength: 10,
                              class: 'pull-right bar-code-input',
                              placeholder: "incluir aqui" %>
        <%- end -%>

      </div>

      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Cód.</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Tam.</th>
            <th>Coleção</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody id="itens_table">
          <%= render partial: 'ajustes/itens/item', collection: @itens %>
        </tbody>
      </table>
    </div>

  </div>

</div>

<%= render partial: 'itens/modals' %>