config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  resources :estoque

  resources :sacolas do
    resources :itens, controller: 'itens_sacola' do
      post 'devolver', on: :collection
    end
    get 'print', on: :member
  end

  resources :vendas do
    resources :itens, controller: 'vendas/itens'
    resources :registros, controller: 'vendas/registros'
    get 'mensal', on: :collection
  end

  resources :compras do
    resources :itens, controller: 'compras/itens'
    resources :registros, controller: 'compras/registros'
  end

  resources :ajustes do
    resources :itens, controller: 'ajustes/itens'
  end

  resources :produtos do
    get :lucro, on: :collection
    resources :etiquetas
  end

  get 'etiquetas' => 'etiquetas#index', as: 'etiquetas'
  post 'etiquetas' => 'etiquetas#print', as: 'print_etiquetas'
  post 'etiquetas/:id/select'   => 'etiquetas#select',   as: 'select_etiqueta'
  post 'etiquetas/:id/unselect' => 'etiquetas#unselect', as: 'unselect_etiqueta'
  post 'etiquetas/unselect'     => 'etiquetas#unselect_all', as: 'unselect_all_etiquetas'
  post 'etiquetas/select'       => 'etiquetas#select_page', as: 'select_page_etiquetas'

  resources :fornecedores do
    post :arquivar, on: :member
  end

  resources :clientes do
    post :arquivar, on: :member
  end

  resources :tamanhos

  resources :colecoes

  resources :linhas

  resources :tipos

  resources :cores

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'dashboard#index'

end

app/controllers/estoque_controller.rb
class EstoqueController < ApplicationController

  def index

    if params[:q]
      params.delete(:q) if params[:q].values.all? { |v| v.blank? }
      session[:itens_q] = params[:q]
    else
      params[:q] = session[:itens_q] if session[:itens_q]
    end

    if params[:q]
      @search = Item.search(params[:q])
      @itens = @search
                .result
                .includes(:tamanho, :cor, produto: [:fornecedor, :colecao])
                .order('fornecedores.nome, produtos.ref, itens.tamanho_id')

      @produtos = @itens.group_by { |i| i.produto }
    else
      @search = Item.search
      @itens = Item.none
      @produtos = Item.none
    end
  end

end

app/helpers/estoque_helper.rb
module EstoqueHelper
end

app/views/estoque/index.html.erb
<%= page_header "Estoque" do %>
  <%= link_to icon(:random, '&nbsp;Ajustes de Estoque'), ajustes_path, class: 'btn btn-sm btn-primary' %>
<% end %>

<div class="row">

  <div class="col-md-9">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Ref</th>
          <th>Fornecedor</th>
          <th>Coleção</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @produtos.each do |produto, itens| %>
          <tr>
            <td><b><%= produto.ref %></b></td>
            <td><%= produto.fornecedor.try :nome %></td>
            <td><small><%= produto.colecao.try :descricao %></small></td>
            <td>
              <table class="table table-condensed clean">
                <% itens.each do |item| %>
                <tr>
                  <td style="width: 60px;"><b><%= item.tamanho.try :nome %></b></td>
                  <td><b><%= item.cor.try :nome %></b></td>
                  <td class="right"><small><%= item.barcode %></small></td>
                  <td class="right"style="width: 36px;">
                    <% lb = item.estoque == 0 ? 'label-default' : 'label-success'  %>
                    <span class="label <%= lb %> bigger"> <%= item.estoque %></span>
                  </td>
                </tr>
                <% end %>
              </table>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p class="index_count"><span class="label label-success bigger"><%= @itens.sum(:estoque) %></span> peças em estoque.</p>

  </div>

  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Filtros</h3>
      </div>
      <div class="panel-body">
        <%= simple_form_for @search, url: estoque_index_path, method: 'GET' do |f| %>

          <%= f.input :produto_colecao_id_eq, label: 'Coleção', collection: Colecao.to_select %>
          <%= f.input :produto_fornecedor_id_eq, label: 'Fornecedor', collection: Fornecedor.to_select %>
          <%= f.input :produto_tipo_id_eq, label: 'Tipo', collection: Tipo.to_select %>

          <%= f.input :produto_ref_cont, label: "Ref" %>

          <%= f.input :em_estoque, label: 'Exibir com estoque', as: :boolean %>

          <%= f.submit 'Filtrar', class: 'btn btn-info' %>
          <%= button_tag 'Limpar', class: 'btn btn-default clear' %>
        <% end %>
      </div>
    </div>
  </div>
</div>